################################################################################
# Node-RED Stack or Compose
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
# Login container using NodeRED
  nginx:
    restart: unless-stopped
    image: nginx:stable-alpine
    container_name: nginx
    environment:
      - TZ=Asia/Jakarta
    ports:
      - 80:80
    networks:
      - kp-iot
    volumes:
      - ${PWD}/nginx/default.conf:/etc/nginx/conf.d/default.conf

# Login container using NodeRED
  nodered-login-dev:
    restart: unless-stopped
    build:
      context: ./nodered-login-dev
    image: kp/nodered-login-dev
    container_name: nodered-login-dev
    environment:
      - TZ=Asia/Jakarta
    networks:
      - kp-iot
    volumes:
      - NodeREDLogindata:/data
      - ${PWD}/nodered-login-dev/settings.js:/data/settings.js

# Dashboard container using NodeRED
  nodered-dashboard-dev:
    restart: unless-stopped
    build:
      context: ./nodered-dashboard-dev
    image: kp/nodered-dashboard-dev
    container_name: nodered-dashboard-dev
    environment:
      - TZ=Asia/Jakarta
    networks:
      - kp-iot
    volumes:
      - NodeREDdata:/data
      - ${PWD}/nodered-dashboard-dev/settings.js:/data/settings.js

#MQTT container using Mosquitto
  mosquitto-broker:
    restart: unless-stopped
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    environment:
      - TZ=Asia/Jakarta
    ports:
      - 1883:1883
    networks:
      - kp-iot
    volumes:
      - ${PWD}/mosquitto-broker/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - Mosquittodata:/mosquitto/data
      - Mosquittodata:/mosquitto/log

#Database container using MariaDB
  mariadb:
    restart: unless-stopped
    image: mariadb
    container_name: mariadb
    environment:
      - TZ=Asia/Jakarta
      - MYSQL_ROOT_PASSWORD=@dminKPIoTDB123
      - MYSQL_USER=nodered
      - MYSQL_PASSWORD=kpiot123
      - MYSQL_DATABASE=iotData
#   expose:
#      - 3306
    ports:
      - 3306:3306
    networks:
      - kp-iot
    volumes:
      - MariaDBdata:/var/lib/mysql
#Web UI to manage database using Adminer
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - kp-iot

#List of Volume
volumes:
#Volume for Login
  NodeREDLogindata:
    external: true
    name: NodeREDLogindata

#Volume for Dashboard
  NodeREDdata:
    external: true
    name: NodeREDdata

#Volume for MQTT
  Mosquittodata:
    external: true
    name: Mosquittodata

#Volume for Database
  MariaDBdata:
    external: true
    name: MariaDBdata

#Network
networks:
  kp-iot:
